[package]
name = "dogwatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.18", features = ["derive"] }
dbus = "0.9.6"
signal-hook = "0.3.14"
crossbeam-utils = "0.8.11"
