name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libbus deps
      run: sudo apt install libdbus-1-dev
    - name: Run tests
      run: cargo test --test dogwatch_test
    - name: Build
      run: cargo build --release
    - name: Strip Debug
      run: strip -s ./target/release/dogwatch
    - name: Install cargo generate rpm
      run: cargo install cargo-generate-rpm
    - name: Build rpm
      run: cargo generate-rpm
    - uses: actions/upload-artifact@v3
      with:
        name: dogwatch.rpm
        path: ./target/generate-rpm/dogwatch*.rpm
